spring:
  cloud:
    gateway:
      routes:
        - id: USER-SERVICE
          uri: lb://USER-SERVICE
          predicates:
            - Path=/users/**
          filters:
            - name: CircuitBreaker
              args:
               name: USER-SERVICE
               fallbackuri: forward:/userServiceFallBack
        - id: DEPARTMENT-SERVICE
          url: lb://DEPARTMENT-SERVICE
          predicates:
            - Path=/departments/**
          filters:
            - name: CircuitBreaker
              args:
               name: DEPARTMENT-SERVICE
               fallbackuri: forward:/departmentServiceFallBack